version: "3"
   
services:
  ner-node:
    build: 
      context: .
      dockerfile: deploy_node.Dockerfile
    container_name: ner_node_container
    ports:
      - "8080:8080"
    volumes: 
        - ./ui:/app
        - /app/node_modules

  ner-python:
    build: 
      context: .
      dockerfile: deploy_python.Dockerfile
    container_name: ner_python_container
    volumes:
        - ./annotator:/app